### PR TITLE
First pass at ringdown plots

### PR DESCRIPTION
**Pull request by danbek**
Matt,

This works, BUT ... it is god-awful slow, just killing my CPU. This is using chrome, but running in a linux VM on my crappy windows laptop, but also only retrieving data every 5 seconds instead of every second.

When I commented out the two nvd3 tags for the ringdown plots, the cpu usage went way down, so it looks like the rendering is the problem.

I don't really understand what the problem is, it seems like 2000 data points isn't that many. Well, I guess it's more like 20,000 given the five cells and two plots ... but still.

Let me know whether this is a dog for you too.

### CODE REVIEW

**Comment by lo-co** [comment]
OK...so now that I am looking at this I think I know what is wrong with ALL of our plotting.  I really believe that what we want to do is to render one time on data update, but on each of these charts, we are rerendering maybe 5+ times each cycle.  Still don't have a solution though.

**Comment by lo-co** [comment]
OK...I think that I am almost there but it is now about 2.  I think that we want to call an ``updateWithData(data)`` using the ``api`` attribute, but I seem to be off somewhere.  Code is not checked in but I will let you know if it works.

https://github.com/krispo/angular-nvd3/issues/37

**Comment by lo-co** [comment]
Now that I think about it, I am certain the problem is in how the data is dumped into the ``[{x,y}]]`` pairs.  Since you have tied the data to the two variables to ``ringdownAvg`` and ``ringdownFit`` and then proceed to update them within the controller, you are firing a render event at every point.  If you are going to do this in the controller, update within a function and then feed the results of that function into the bound data.  Or, better yet, leave the computational stuff to the service.  Testing now...

**Comment by lo-co** [comment]
OK, so my solution made things a leetle beet better... but not enough.  This doesn't make any sense.  Put an issue up on stackoverflow:

http://stackoverflow.com/questions/32785163/nvd3-used-with-angular-nvd3-is-slooooowwwww

**Comment by danbek** [comment]
Ah, if it is rendering on every change to `ringdownFit` and `ringdownAvg`,
that would clearly be a big problem. But it's not clear to me why this
would happen ... does angular have capability to watch an object and take
action every time it changes?

But this would be an easy fix ... just build everything up into a temp
object, and then only change `ringdownFit` and `ringdownAvg` at the very
end.

We are going to aspen this weekend, I might look at this while there, but
we'll be back late sun afternoon.

Dan

On Fri, Sep 25, 2015 at 7:59 AM, Matt Richardson <notifications@github.com>
wrote:

> Now that I think about it, I am certain the problem is in how the data is
> dumped into the [{x,y}]] pairs. Since you have tied the data to the two
> variables to ringdownAvg and ringdownFit and then proceed to update them
> within the controller, you are firing a render event at every point. If you
> are going to do this in the controller, update within a function and then
> feed the results of that function into the bound data. Or, better yet,
> leave the computational stuff to the service. Testing now...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lo-co/exscalabar/pull/41#issuecomment-143231727>.
>



-- 
Dan Becker

**Comment by lo-co** [comment]
Don't look at this just yet.  I am discussing this with some others considerably smarter than me.  I will update you.  Could be we will move to canvas.  Ugh.

**Pull request merged**
